---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: "Python ${{ matrix.python }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: "3.9"
    strategy:
      matrix:
        name: [py37, py38, py39, py310]
        include:
        - name: py37
          python: 3.7
        - name: py38
          python: 3.8
        - name: py39
          python: 3.9
          coverage: "--cov"
        - name: py310
          python: "3.10"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
          python-version: "${{ matrix.python }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] virtualenv pytest-cov codecov
          python -m pip install --upgrade -r requirements.txt
          python -m pip install .
      - name: "Run pytest targets for ${{ matrix.python }}"
        run: |
          pytest --cov=zhinst.labber tests/
      - name: codecov
        if: matrix.coverage
        run: |
          codecov
